const SKILLS_BY_DEPARTMENT = {
  "B.Sc.IT": [
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "SQL",
    "Python",
    "Java",
    "DSA",
    "OOP",
    "REST APIs",
  ],
  "B.Sc.DS": [
    "Python",
    "R",
    "Machine Learning",
    "Data Analysis",
    "TensorFlow",
    "Pandas",
    "NumPy",
    "SQL",
    "Tableau",
    "Statistics",
  ],
  BAF: [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  BFM: [
    "Excel",
    "Financial Analysis",
    "Accounting",
    "Tax Planning",
    "Investment Analysis",
    "Risk Management",
  ],
  BMS: [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  BBI: [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  BAMMC: [
    "Business Strategy",
    "Marketing",
    "HR Management",
    "Operations",
    "Communication",
    "Leadership",
  ],
  "M.Sc.IT": [
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "SQL",
    "Python",
    "Java",
    "DSA",
    "OOP",
    "REST APIs",
  ],
  "M.Com(AA)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(B&A)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(B&F)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  "M.Com(BM)": [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
  MAEMA: [
    "Advanced Financial Analysis",
    "Auditing",
    "Business Law",
    "Economics",
    "Strategic Management",
  ],
};

export default SKILLS_BY_DEPARTMENT;
